### PR TITLE
/time_region_value: clicking on SVG anchors fails

### LINKED ISSUE #319: /time_region_value: clicking on SVG anchors fails

### PR DESCRIPTION
**Pull request by saabi**
Closes #319

### CODE REVIEW

File: packages/components/time_region_value/src/node_modules/utils/url.js [hunk 1]
```diff
@@ -1,3 +1,12 @@
...
+import {isServerSide} from 'utils/env';
+
+export const makeURL = (base, id, year) => {
+	const path = year
+		? `${base}/${id}/${year}`
+		: `${base}/${id}`;
+	if (isServerSide) {
+		return path;
+	}
+	const {protocol, host} = location;
```
Comment (mindrones) [inline packages/components/time_region_value/src/node_modules/utils/url.js]: I'd leave a blank line around the `if` and the `const` for readability

File: packages/docs/site/src/routes/components/_layout.svelte [hunk 2]
```diff
@@ -10,7 +10,7 @@
 			<div class='distancer'>
 				<h2>{key}</h2>
 				{#each value as {slug, title}}
-					<a href='components/{slug}'>
+					<a href='components/{slug}' rel='prefetch'>
```
Comment (mindrones) [inline packages/docs/site/src/routes/components/_layout.svelte]: multiple attributes needs to be on their own line

File: packages/docs/site/src/routes/components/index.svelte [hunk 3]
```diff
@@ -22,7 +22,7 @@
 <ul>
 	{#each components as component}
 		<li>
-			<a rel='prefetch' href='components/{component.slug}'>
+			<a href='components/{component.slug}' rel='prefetch'>
```
Comment (mindrones) [inline packages/docs/site/src/routes/components/index.svelte]: multiple attributes needs to be on their own line

**Review by mindrones — APPROVED** [review]
Good to merge after tackling a few comments I left below

**Review by mindrones — APPROVED** [review]
